---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    vagrantfile_erb: Vagrantfile.erb
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.0pre11-1_amd64.deb"
          checksum: "ca0c78cdb0a42a07db36a95fcc802e95cb459b2eb51a83b18f8690d619c3e27a"
        enterprise:
          checksum: ""
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
    vagrantfile_erb: Vagrantfile.erb
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.0pre11-1_amd64.deb"
          checksum: "e14a2a576e85dcb68d01713721b08d31b2dcb64be6a9777562e120564b6e5976"
        enterprise:
          checksum: ""
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    vagrantfile_erb: Vagrantfile.erb
    customize:
      memory: 512
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.0pre11-1.el6.x86_64.rpm"
          checksum: "24cbd215a123294ac7bbf65e9e76a513e0dca704e7362b86149ce9deebcae9f4"
        enterprise:
          checksum: ""
- name: centos-5.10
  driver_config:
    box: opscode-centos-5.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10_chef-provisionerless.box
    vagrantfile_erb: Vagrantfile.erb
    customize:
      memory: 512
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.0pre11-1.el5.x86_64.rpm"
          checksum: "bca839267482db6d290ae6747074a414958dedc3333cc573259d9de511156432"
        enterprise:
          checksum: ""
- name: fedora-19
  driver_config:
    box: opscode-fedora-19
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
    vagrantfile_erb: Vagrantfile.erb
    customize:
      memory: 512
  attributes:
    riak:
      package:
        local:
          checksum: "1672703f40e1d98954f40895c05435385651093e1268905ab46f79f4417b04b4"
        enterprise:
          checksum: ""
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        local:
          filename: ""
        version:
          major: "2"
          minor: "0"
          incremental: "0pre11"
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        url: "http://private.downloads.basho.com/riak_ee"
        version:
          major: "2"
          minor: "0"
          incremental: "0pre11"
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_package
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes: {}
- name: custom_repository
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_repository"
- name: source
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: "2"
        minor: "0"
        incremental: "0pre11"
